### ISSUE TITLE
UnsatisfiedDependencyException for Spring Boot Application

### ISSUE THREAD

**Issue by TakumaFujiwara** [NRequa/EE461L_Jaguar_SSBracket#6]
Currently trying to update dependencies in gradle for RestAPI

java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException
            Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException
                Caused by: org.springframework.beans.factory.BeanCreationException
                    Caused by: org.springframework.beans.BeanInstantiationException
                        Caused by: java.lang.RuntimeException

**Comment by nduggar** [comment]
This appears to be caused when there's another error in creating a Bean. I edited the code with commit defd310 to use the AWS mySQL database, and now the issue is:


com.example.apiREST.ApiRestApplicationTests > contextLoads FAILED java.lang.IllegalStateException: Failed to load ApplicationContext                                                                                                    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating  bean with name 'entityManagerFactory' defined in class path resource [org/spring framework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocatio n of init method failed; nested exception is javax.persistence.PersistenceExcept ion: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested  exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-va lidation: missing table [tournaments]                                                                                                                                         Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] U nable to build Hibernate SessionFactory; nested exception is org.hibernate.tool. schema.spi.SchemaManagementException: Schema-validation: missing table [tourname nts]                                                                                                                                                                              Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema- validation: missing table [tournaments]
--

**Comment by nduggar** [comment]
It turns out that the "missing table" was actually a result of the database in the mySQL instance not ever being selected. Since no database could be selected, no tables could exist, hence the error. I find it problematic that the error mentions nothing about not having a database selected, though. Either way, case closed.
